# Generated by Django 2.1.2 on 2019-03-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularlyPayment',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('is_regist_automaticaly', models.BooleanField()),
                ('amount_per_month', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('acc_bot_uid', models.ForeignKey(db_column='acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, to='sdss.AccBot')),
            ],
            options={
                'db_table': 'regularly',
                'managed': True,
            },
        ),
    ]
