# Generated by Django 2.1.2 on 2019-03-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0002_regularlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularlypayment',
            name='payment_day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
