# Generated by Django 2.1.2 on 2019-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0003_regularlypayment_payment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlypayment',
            name='payment_day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
