# Generated by Django 2.1.2 on 2019-03-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0004_auto_20190317_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularlypayment',
            name='acc_bot_uid_from',
            field=models.ForeignKey(db_column='acc_bot_uid_from', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acc_bot_uid_from', to='sdss.AccBot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regularlypayment',
            name='acc_bot_uid',
            field=models.ForeignKey(db_column='acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='acc_bot_uid', to='sdss.AccBot'),
        ),
    ]
