# Generated by Django 2.1.2 on 2019-04-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0006_auto_20190401_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accbot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='acctop',
            options={'managed': False},
        ),
    ]
