# Generated by Django 2.1.2 on 2019-04-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0007_auto_20190404_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('asset_no', models.CharField(default='shixxxx', max_length=20, null=True)),
                ('asset_name', models.CharField(max_length=45)),
                ('get_date', models.CharField(max_length=10)),
                ('acquisition_cost', models.IntegerField()),
                ('carrying_value', models.IntegerField()),
                ('amortization_way', models.CharField(default='定額法', max_length=10)),
                ('amortization_term_in_month', models.IntegerField()),
                ('passed_months', models.IntegerField()),
                ('amortization_cost_per_month', models.IntegerField()),
                ('amortizated_total_cost', models.IntegerField()),
                ('sales_income', models.IntegerField()),
                ('is_using', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('acc_bot_uid', models.ForeignKey(db_column='acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fa_acc_bot_uid', to='sdss.AccBot')),
            ],
            options={
                'db_table': 'fixed_asset',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='regularlypayment',
            name='acc_bot_uid',
            field=models.ForeignKey(db_column='acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rp_acc_bot_uid', to='sdss.AccBot'),
        ),
    ]
