# Generated by Django 2.1.8 on 2019-04-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0008_auto_20190418_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=45)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'account_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountGroupList',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('acc_bot_uid', models.ForeignKey(db_column='acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ag_acc_bot_uid', to='sdss.AccBot')),
                ('account_group_uid', models.ForeignKey(db_column='account_group_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_group_uid', to='sdss.AccountGroup')),
            ],
            options={
                'db_table': 'account_group_list',
                'managed': True,
            },
        ),
    ]
