# Generated by Django 2.1.2 on 2020-05-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdss', '0009_accountgroup_accountgrouplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidList',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('acc_bot_uid', models.ForeignKey(db_column='acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pp_acc_bot_uid', to='sdss.AccBot')),
                ('account_group_uid', models.ForeignKey(db_column='account_group_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pp_account_group_uid', to='sdss.AccountGroup')),
                ('br_acc_bot_uid', models.ForeignKey(db_column='br_acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pp_br_acc_bot_uid', to='sdss.AccBot')),
                ('cr_acc_bot_uid', models.ForeignKey(db_column='cr_acc_bot_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pp_cr_acc_bot_uid', to='sdss.AccBot')),
                ('journal_uid', models.ForeignKey(db_column='journal_uid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pp_journal_uid', to='sdss.Journal')),
            ],
            options={
                'db_table': 'prepaid_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WantsList',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('is_delete', models.BooleanField()),
                ('planning_date', models.CharField(max_length=10)),
                ('buy_date', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'wants_list',
                'managed': True,
            },
        ),
    ]
