# Generated by Django 2.1.2 on 2019-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meas',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('temp', models.FloatField()),
                ('pres', models.FloatField()),
                ('hum', models.FloatField()),
            ],
            options={
                'db_table': 'geo_meas',
                'managed': True,
            },
        ),
    ]
