# Generated by Django 2.1.2 on 2019-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meas',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
